name: cfv_database_and_deck_builder
description: "A Mobile App for CardFight VAnguard Database and Deck Builder"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:
  equatable:
  shared_preferences:
  http:
  intl:
  go_router:
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
